version: '3.8'

services:
  muebleswow:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - PORT=80
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-muebleswow123}
      - DATABASE_URL=postgresql://muebleswow:muebleswow123@localhost:5432/muebleswow
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
