[providers]
# Forzar que use Docker en lugar de detecci칩n autom치tica
providers = ["dockerfile"]

[phases.setup]
# No instalar nada autom치ticamente
nixPkgs = []
aptPkgs = []

[phases.build]
# No hacer build autom치tico
cmds = []

[phases.start]
# Usar nuestro script de inicio personalizado
cmd = "./start.sh"
